// ...existing code...
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div>
          <nav
            style={{
              display: "flex",
              justifyContent: "space-between",
              alignItems: "center",
              padding: "0.75rem 1rem",
              borderBottom: "1px solid #eaeaea",
              background: "white",
            }}
          >
            <div style={{ fontWeight: 700 }}>March Madness</div>
            <div style={{ display: "flex", gap: "1rem" }}>
              <Link href="/">Brackets</Link>
              <Link href="/brackets">Scoreboard</Link>
              <Link href="/about">Winners</Link>
            </div>
          </nav>
        </div>
        {children}
      </body>
    </html>
  );
}
//